### ISSUE TITLE
Can you please contact me

### ISSUE THREAD

**Issue by wernervz** [IBM/developer#1]
Hi, I'm the lead engineer on the WithWatson program. Can you please contact me directly at wjvanzyl@us.ibm.com.  

We would like to publish some design/code patterns that are specific to some of our strategic partners.  I have some question on tagging, format, content etc.

**Comment by stevemar** [comment]
@wernervz i'll give you a shout and cc some of our offering managers.

**Comment by neilmack** [comment]
@stevemart Steve, can we close this issue?

**Comment by stevemar** [comment]
@neilmack yes. Werner and I have spoken.
