### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by dionj** [IBM/developer#102]
1. No longer exists:  https://developer.ibm.com/patterns/create-a-movie-recommendation-system/
2. Please update the associated link at this website: https://developer.ibm.com/code/components/twilio/  --->  Create a movie recommendation system

**Comment by stevemar** [comment]
just chiming in, that the correct link for the first is: https://developer.ibm.com/patterns/creating-a-movie-recommendation-with-turi-create-on-watson-studio-coreml/

**Comment by mcorbin-ibm** [comment]
Done, redirect in place (thanks @stevemar for the quick posting of the correct link).
