### ISSUE TITLE
How do I become a IBM Developer blogger?

### ISSUE THREAD

**Issue by jamesbeltonIBM** [IBM/developer#11]
Hi,
I used to regularly write and post blogs on developerWorks but am now unable to do so with the transition to IBM Developer. How do I become a blogger on IBM Developer and gain access to upload my content?
Kind regards
James

**Comment by neilmack** [comment]
Hi James, thanks for your question. For IBM employees, you can contribute content through a form on w3 Developer. Just do a search from the intranet home page -- if you have any issues, ping me and I'll get you to the right spot.

**Comment by GrahamHannington** [comment]
Same question, but for people who are not IBM employees?

Some background to my question...

So far, I have published two dW recipes:

- [The Lifecycle of an IMS Connect Transaction](https://developer.ibm.com/recipes/tutorials/the-lifecycle-of-an-ims-connect-transaction/) (494 views)
- [Report IMS transaction performance using forms in IBM IMS Performance Analyzer for z/OS](https://developer.ibm.com/recipes/tutorials/report-ims-transaction-performance-using-forms-in-ibm-ims-performance-analyzer-for-z-os/) (559 views)

I like the freedom that dW recipes offer—to publish content directly—but the prescribed recipe structure is not an ideal fit for content I'm considering for future publication.

I was considering asking on the dW site about creating articles, but upon revisiting the site, I see that it's in transition, rebranding.

I'd like to contribute content to the IBM Developer site about using IBM-brand products. That content might not necessarily match the step-by-step structure of a recipe; it might be better suited to the less-rigid structure of an "article".

How do I publish content like that on the IBM Developer site? Blogging? (Do I create my own personal IBM Developer blog? How?) I don't plan to be a frequent blogger. Is there a way to publish articles, separate from blogging?

What is the future of dW recipes? Will they be migrated over to IBM Developer? I've read the FAQ, but that point is not clear to me (with apologies if I missed it). Do I now publish tutorials instead of recipes? How?

I understand this is all a work in progress, but I thought I'd mention that the "Submit content" link on the IBM Developer site leads to a page titled "Submission of Content Agreement" that doesn't describe what types of content users can submit, or how to submit it. Where can I find that information?

**Comment by GrahamHannington** [comment]
In case your reaction to my previous comment was "tl;dr":

- I am a member of a team that develops IBM products.
- I am not an IBM employee. I do not have direct access to the IBM intranet.
- **What types of content can I contribute to IBM Developer, and how?** Feel free to ask me to raise this as a separate issue.

**Comment by jamesbeltonIBM** [comment]
Hi Graham,
 
You can do this by signing up to the IBM Developer community. Check out this link and read the Starter Guide - this will tell you the kinds of content that you can contribute - it includes coding patterns and blogs.
 
https://developer.ibm.com/community/
 
Hope that helps!
 
Kind regards,
 
James
 
James Belton CITP MBCS
Global Technical SME - Watson & Cloud Platform
IBM Hybrid Cloud
 
Mobile: +44 7500 76 36 44 | IBM Internal:  37263173 | E-mail:  james.belton@uk.ibm.com
 
Find me on LinkedIn | Follow me on Twitter 

 
    
 
IBM United Kingdom Limited | Registered in England and Wales with number 741598 | Registered office: PO Box 41, North Harbour, Portsmouth, Hants. PO6 3AU
 
 
----- Original message -----From: Graham Hannington <notifications@github.com>To: IBM/developer <developer@noreply.github.com>Cc: James Belton <james.belton@uk.ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBM/developer] How do I become a IBM Developer blogger? (#11)Date: Tue, Nov 20, 2018 3:20 AM 
In case your reaction to my previous comment was "tl;dr":
        I am a member of a team that develops IBM products.        I am not an IBM employee. I do not have direct access to the IBM intranet.        What types of content can I contribute to IBM Developer, and how? Feel free to ask me to raise this as a separate issue.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. 
 Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU

**Comment by neilmack** [comment]
@GrahamHannington Hi Graham! Thank you very much for your query. It definitely isn't a tl;dr situation. We're currently assessing all our content types and processes as we continue the evolution to IBM Developer. The short answer to your question is that the new IBM Developer will continue to welcome submissions from non-IBMers; I'll ask our content strategist to provide more details to answer your specific questions. However, with it being U.S. Thanksgiving week, it might take a bit longer than normal to get you a full response. Please bear with us, and apologies for my temporary tap dance.

@jamesbeltonIBM James, thanks very much for the pointer to IBM Coder community page! That's a great place to start. We're also in the process of updating that information to reflect our new channels and processes. 

It's a major effort to modernize our site but we're confident the end result will a dynamic, collaborative, and valuable environment for developers. We'll post more details asap, and we really appreciate your interest and feedback.

**Comment by GrahamHannington** [comment]
@jamesbeltonIBM,

Thanks for the pointer. With apologies, I probably should have mentioned that I'd already read that _**IBM Coder** Starter Guide_ and signed up with IBM Coder (as per the link you supplied), but I didn't want to make my comment any longer.

**Unfortunately, the _Starter Guide_ doesn't answer many of my questions.** The _Guide_ mentions code patterns, blogs, and tutorials as types of content that can be contributed, but not _how_. I thought perhaps this might be clearer after logging in to IBM Coder, but the IBM Coder ("IBM Coder Program") site (https://ibmcoders.influitive.com/) is different to the IBM Developer site. The IBM Coder site navigation lists Challenges, Discussions, and Referrals, but not code patterns, blogs, or tutorials.

I don't know what you mean by this:

> signing up to the IBM Developer community.

As mentioned, I've signed up to IBM Coder, but that doesn't appear to offer me the ability to contribute the types of content I'm interested in here.

I can sign into the [developerWorks Recipes](https://developer.ibm.com/recipes/) "sub-branded" site of IBM Developer—as I have done in the past to create recipes—but I can't see any way to sign in to the "main" [IBM Developer site](https://developer.ibm.com/).

I can see that the IBM Developer site shows code patterns, articles, tutorials, and recipes. It appears I can still create a recipe (as I have done twice in the past)—the "Create a recipe" button is still there—but I can't see how to contribute any of the other content types.

It's possible that I might have code patterns to contribute in the future (I already have at least one GitHub repo that I could reuse for this purpose), but for now, I'm more interested in providing articles, or similar written content that might include code _snippets_.

@neilmack,

Thanks for pitching in. You wrote:

> We're  also in the process of updating that information to reflect our new channels and processes.

Understood: it's a work in progress. I get the general idea that you're in the process of coalescing various "programs"/channels under the IBM Developer brand.

> We'll post more details asap

Yes, please.

> we really appreciate your interest and feedback.

You're welcome. I already write IBM product user documentation that is published in IBM Knowledge Center. I want to augment that documentation with content published via other channels, such as [videos on the IBM Z YouTube channel](https://www.youtube.com/playlist?list=PLz9fRjdHqVyyDgjzrNP-cihvF6JoxrFJt), and content on IBM Developer (my two dW recipes are a "toe in the water"). I'm not an IBM employee, but I write about IBM-brand products, and it makes sense to me to publish that content via IBM-brand channels where possible, although not necessarily exclusively; I've also posted such content to SlideShare. I'm also considering LinkedIn articles—among other non-IBM channels—as a possibility, depending on my experience here.

Here's my current understanding:

* I can still create recipes. (I really like being able to contribute directly this way, without intermediaries introducing delays, double-handling/retagging/reformatting—and potentially garbling—the content. I'd like the same freedom to directly create articles, without the restrictions of the prescriptive "ingredients/step-by-step" recipe structure. Given that freedom, I can live with a "community-created content" disclaimer.)
* I don't know how to contribute any other type of content—such as blog posts, articles, or tutorials—to IBM Developer.
* I don't know your future plans for recipes on the IBM Developer site. Will they be replaced by tutorials? Should I move my existing dW recipes to IBM Developer tutorials (that is, when I can create tutorials), and then delete those recipes? Or will you automatically do that for me? (In which case, I hope that doesn't introduce any formatting glitches.)

**Comment by neilmack** [comment]
@GrahamHannington Graham, just an update to reaffirm what you itemized. Our content strategist confirms that recipes will continue to be a "community-created" publishing option. Publishing other content types such as articles is not yet available for non-IBM developers but we do hope to make that option available soon. We'll provide full details on the site as soon as they become available.

**Comment by GrahamHannington** [comment]
@neilmack,

Thanks very much for the update. That's two items of good news for me. I'm about to start drafting a new recipe. I look forward to other options being available to non-IBMers; I'll keep an eye on the site for details.

**Comment by GrahamHannington** [comment]
@neilmack,

Re:

> Our content strategist confirms that recipes will continue to be a "community-created" publishing option.

I've started drafting a new recipe. I've noticed, as I'm entering the recipe title etc, that the title of the browser tab is "Tutorials Archive - developerWorks Recipes". Perhaps I'm overthinking this, but the word "Archive" in that title evokes a sense of deprecation. Unfounded?

**Comment by LindaMeyer** [comment]
@GrahamHannington Hi Graham. Thanks for taking the time to share your input. That is a valid comment. We appreciate your feedback and will forward that to the development team.
