### ISSUE TITLE
Broken dependencies in Tutorial "MQ JMS application development with Spring Boot"

### ISSUE THREAD

**Issue by smpby** [IBM/developer#113]
The maven dependencies in [Tutorial](https://developer.ibm.com/tutorials/mq-jms-application-development-with-spring-boot/) in Step 4 use the wrong kind of minus/dash.  
It's like this in the article:
````
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson‑databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ibm.mq</groupId>
            <artifactId>mq‑jms‑spring‑boot‑starter</artifactId>
            <version>2.0.0</version>
        </dependency>
````
But should be like this:
````
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ibm.mq</groupId>
            <artifactId>mq-jms-spring-boot-starter</artifactId>
            <version>2.0.0</version>
        </dependency>
````
-> Looks the same, but is different (the second snipped actually work's unlike the one given )

A colleague of mine spent half a day trying to find this error, so a fix would be appreciated :)

**Comment by mcorbin-ibm** [comment]
Thanks for reporting the issue with the code block.  I copied/pasted the code that you provided, and updated it in the tutorial.    Please let me know if this issue is fixed!

**Comment by smpby** [comment]
Thanks for updating the post. :)
Now the dependencies work, as they should.
