### ISSUE TITLE
All links for IBM security broken

### ISSUE THREAD

**Issue by Ryan1292** [IBM/developer#118]
I am trying to download IBM i2 analyst's notebook premium and I noticed all the links on the IBM security section of your website do not work. How do I get a copy of the software?

**Comment by neilmack** [comment]
Hey @Ryan1292, can you provide the URL of a page where the download is broken? That will help us resolve the issue.

**Comment by Ryan1292** [comment]
Hi Neil,
I've heard back from the Academic Initiative people and they seemed to have fixed the issue.
Thanks for your help.


Ryan Glover

Casual Academic


Centre for Forensic Science, MAPS

University of Technology Sydney

PO Box 123 Broadway NSW 2007 Australia

[cid:973fb1fc-4fa1-450c-9869-66d4db774e90]

________________________________

**Comment by neilmack** [comment]
Glad to hear it's resolved -- thanks, Ryan!
