### ISSUE TITLE
Broken link to redeem voucher from Coursera

### ISSUE THREAD

**Issue by orsdanilo** [IBM/developer#119]
I completed the challenges for Applied AI, but when I clicked on the link to redeem the Voucher for the Coursera subscription, I got the following message from the Coursera website:
"Sorry
Looks like you found a page that does not exist or the URL was mistyped by accident."

The links starting in "nopanic.ai" are also down.

**Comment by neilmack** [comment]
Danilo, can you provide the URL of the page you were on when you encountered the broken link? That will help us track down and resolve the issue. Thanks.

**Comment by orsdanilo** [comment]
The URL is the following:
[link removed]

**Comment by neilmack** [comment]
@orsdanilo Danilo, the link should now be working. Please try again.

**Comment by orsdanilo** [comment]
It worked! Thanks, Neil!
