### ISSUE TITLE
Unable to download documentation resources

### ISSUE THREAD

**Issue by swlinn** [IBM/developer#130]
The following article's code sample resources cannot be downloaded.  Only the article .pdf can be downloaded.
https://www.ibm.com/developerworks/websphere/library/techarticles/1208_poon1/1208_poon1.html

**Comment by mcorbin-ibm** [comment]
@swlinn Please try again now, to download the sample code.  We think we have fixed the issue.

**Comment by swlinn** [comment]
@mcorbin-ibm Thank you, I can now download the resources.  Closing the issue.
