### ISSUE TITLE
Downloadable resources

### ISSUE THREAD

**Issue by chengm349** [IBM/developer#133]
I am reading the article at https://developer.ibm.com/tutorials/au-memorymanager/ and we are supposed to be able to get its src from Downloadable resources. please kindly give the right link.

Thanks,

**Comment by chengm349** [comment]
Does anyone know?

**Comment by LinzSTP** [comment]
@chengm349 We have fixed the links and you should now be able to download the files. Thank you.

**Comment by chengm349** [comment]
I got the code but it's buggy.
