### ISSUE TITLE
App Connect component should present videos on IBM Developer channel

### ISSUE THREAD

**Issue by AnimatIan** [IBM/developer#139]
https://developer.ibm.com/videos/category/app-connect/ returns "There are no published Videos at this time."

The IBM App Connect component on IBM Developer should offer videos from the App Connect playlists on Youtube in the IBM Developer channel:

- "App Connect" (Designer/IBM Cloud) https://www.youtube.com/playlist?list=PLzpeuWUENMK2Q77xr7QkvLxU5YxOJxVSH
- "App Connect Enterprise" https://www.youtube.com/playlist?list=PLzpeuWUENMK3ttFsZraPRNN4XhkoS2Hte

**Comment by mcorbin-ibm** [comment]
Exchanged emails about this request.  Closing this issue.
