### ISSUE TITLE
Spelling Mistake in Figure of your Article

### ISSUE THREAD

**Issue by subtext2healthcare** [IBM/developer#14]
I can see a spelling mistake in Figure 1. 
of this article of yours. It should have been State/Action, instead it is only State/ction. 

https://developer.ibm.com/articles/cc-models-machine-learning/

![models of machine learning](https://user-images.githubusercontent.com/34882786/46750744-dac7c300-cce2-11e8-8892-10ba5e4d11d6.png)

**Comment by neilmack** [comment]
Fixed.
