### ISSUE TITLE
Broken link of Test Image Folder of Visual Recognition Challenge

### ISSUE THREAD

**Issue by JGabrielGruber** [IBM/developer#143]
Hello,
There's a step in the [Visual Recognition Challenge](https://developer.ibm.com/tutorials/visual-recognition-challenge/) which requires the [test images folder](https://developer.ibm.com/tutorials/visual-recognition-challenge/testimages/), as mentioned here: 

> Load the images from the test images folder into the Test page by clicking and dragging the images into the Test page.

But, the link is broken.
This is the link: https://developer.ibm.com/tutorials/visual-recognition-challenge/testimages/

**Comment by TheVictorMunoz** [comment]
I'm having the same problem.

**Comment by aimendez** [comment]
Same issue here. Impossible to complete the challenge for now.

**Comment by Mohamed-AboTaleb** [comment]
The same problem

**Comment by sethtara** [comment]
same here

**Comment by mani56005** [comment]
Same problem, when we can expect it to be resolved?

**Comment by neilmack** [comment]
@Tarakant-seth @aimendez @victormunozalbornoz @JGabrielGruber @Mohamed-AboTaleb @mani56005 Thank you all for pointing out the broken link! It's fixed now -- please try again.

[Edit]: We've updated the tutorial to include the images that you need to add to your test page.

**Comment by JGabrielGruber** [comment]
Hello @neilmack,
Hmmm, this repository seems to be private, it redirects me to login with a w3id account, which I don't have.
I cannot access the images by this way, could you please find another way? Thank you!

https://w3id.sso.ibm.com/auth/sps/samlidp2/saml20/logininitial?RequestBinding=HTTPPost&PartnerId=https://github.ibm.com&NameIdFormat=email&Target=https://github.ibm.com

**Comment by neilmack** [comment]
@JGabrielGruber We'll get it sorted. For the time being, I'm attaching the two images here: 

![test1](https://user-images.githubusercontent.com/42751451/67644098-abd3bd80-f8f4-11e9-89dc-1724d8922708.jpeg)
![test2](https://user-images.githubusercontent.com/42751451/67644099-abd3bd80-f8f4-11e9-8c6b-349838fa2b40.jpeg)

**Comment by JGabrielGruber** [comment]
Thank you, @neilmack, very much!

**Comment by neilmack** [comment]
Note to all who have posted in the thread, we've updated the tutorial to include the images that you'll need to copy into the Test page. We're sorry for the inconvenience -- we really appreciate you taking the time to notify us of the issue. Good luck with the challenge and the Digital Developer Conference!
