### ISSUE TITLE
Ansible AWX - Outdated Information

### ISSUE THREAD

**Issue by lokeshkamalay** [IBM/developer#152]
https://developer.ibm.com/articles/automation-using-ansible-awx-gui/

The instructions mentioned in this article are not accurate anymore.
1. awx-repo path is no more valid.  It seems it has been changed from `awx` to `ansible-awx`.
2. Installing awx now changed to ansible-awx??
 `yum install -y awx`
3. No `awx-manage` found in the said path.  I found this under, `/opt/rh/rh-python36/root/usr/bin/awx-manage`
4. Some Python packages are not properly loaded eg:
  - psycopg2
  - sqlparse
5. Importing data into database is failing with below git error.  Git is in path for both awx and sudo users.
```
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()
```

**Comment by MrMEEE** [comment]
Please refer to https://awx.wiki for the REAL installation and upgrade guide..

**Comment by lokeshkamalay** [comment]
Thanks for the update..
