### ISSUE TITLE
Broken Link on Realtime visitor analysis tutorial page

### ISSUE THREAD

**Issue by dipoojo55** [IBM/developer#159]
The 'provided source code' link on the realtime-visitor-analysis-with-kafka page is bbroken.

https://developer.ibm.com/tutorials/realtime-visitor-analysis-with-kafka/#prerequisites

Please fix. Thank you Kindly!

**Comment by neilmack** [comment]
Hey @dipoojo55, the link is now fixed. Thanks very much for taking the time to notify us!

**Comment by dipoojo55** [comment]
Thanks! Much appreciated.
