### ISSUE TITLE
Need to update API description for Db2

### ISSUE THREAD

**Issue by blhatdeibmcom** [IBM/developer#16]
I'm a content designer working on documentation for Db2 Warehouse. 
Due to changes to the product, the following page needs to be updated:
https://developer.ibm.com/static/site-id/85/api/db2wh/#database
The **rscript : Run R scripts** section needs to be deleted.
How do I best go about doing that?

**Comment by neilmack** [comment]
Craig, thanks for your question. We're tracking down the content owner and will put you in touch with that person asap.

**Comment by neilmack** [comment]
@blhatdeibmcom Apologies for the delay in tracking this down. The owner of the page in question is Jeff Levitt from IBM Hybrid Cloud. If you send him an email, he can make the update for you.

**Comment by blhatdeibmcom** [comment]
Thank you!
--Craig

IBM Deutschland Research & Development GmbH 
Vorsitzende des Aufsichtsrats: Martin Jetter
Geschäftsführung: Dirk Wittkopp
Sitz der Gesellschaft: Böblingen 
Registergericht: Amtsgericht Stuttgart, HRB 243294
