### ISSUE TITLE
SSL communication disabled for eclipse.bluemix.net

### ISSUE THREAD

**Issue by amoriba** [IBM/developer#164]
Hi,

I am not sure this is right place to report. However it is related to IBM site.
IBM distribute Eclipse-SDK through IBM Cloud.
http://eclipse.bluemix.net/
Since the web app doen't support SSL, user attempting grab Eclipse must see security warning from browser. (both FireFox and Chrome.)
We feel this will be good if you enable SSL. Other web site distributing Eclipse-SDK are supporting SSL of course.

![image](https://user-images.githubusercontent.com/7568509/69302924-82d9ea80-0c5e-11ea-9340-69c9cac1677d.png)

Thank you.

**Comment by kitlo** [comment]
We have enabled HTTPS secure connection to IBM Distribution of Eclipse Package Downloads site. Please check if it's working as you expected and close the issue if it's resolved. Thanks for reporting the issue!
https://eclipse.bluemix.net/

**Comment by amoriba** [comment]
Hi Kitlo,
Thank you for your action. I verified the solution using Let's Encrypt.
However there is a mixed content which doesn't use HTTPS.  So my FireFox complained about it.
It seems like there is XMLHttpRequest with events query over HTTP.
And initiated by js code issue from https://cdn.optimizely.com/js/3697594377.js. (there are multiple http://eclipse.bluemix.net/ without "S". ).

![image](https://user-images.githubusercontent.com/7568509/72780401-1da47480-3c62-11ea-9f34-25dae57c2085.png)


Thank you.

**Comment by kitlo** [comment]
@amoriba I updated some URLs referenced by the index.html. Please try again.

**Comment by amoriba** [comment]
@kitlo 
It seems good for now.
However when I clicked on IBM logo in eclipse.org download page, destination page is still HTTP instead of HTTPS. Could you check it ?
![image](https://user-images.githubusercontent.com/7568509/73044203-e32e1800-3eab-11ea-91d8-1406acd33f94.png)
https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2019-12/R/eclipse-inst-win64.exe

![image](https://user-images.githubusercontent.com/7568509/73044243-1bcdf180-3eac-11ea-8492-52a60581e642.png)

**Comment by kitlo** [comment]
@amoriba I'm aware of that. It's because I had the HTTPS secure connection setup just recently AFTER the Eclipse Package Downloads mirror registration. Once I feel confident with the HTTPS secure connection setup, the next step is to either contact the Eclipse Foundation webmaster to update the mirror registration, or redirect all HTTP traffics to HTTPS on our server. I will follow-up on that.

**Comment by kitlo** [comment]
Eclipse Foundation webmaster updated the link. It should now forward to the HTTPS secure connection. Please verify.

**Comment by amoriba** [comment]
Hello Kitlo,
I confirmed the situation was fixed now. Thank you for your action!
