### ISSUE TITLE
Websphere MQ article missing

### ISSUE THREAD

**Issue by krupa38** [IBM/developer#169]
Several documents refer to "http://www.ibm.com/developerworks/websphere/library/techarticles/0906_schneider/0906_schneider.html" and an accompanying PDF "0906_schneider-pdf.pdf". Unfortunately this link cannot be resolved. It is an article about MQ for z/OS and RACF.
Can you make it reappear?
Thanks and regards!

**Comment by mcorbin-ibm** [comment]
The following article, and its PDF file, has been restored to the developerWorks archives:
https://www.ibm.com/developerworks/websphere/library/techarticles/0906_schneider/0906_schneider.html
