### ISSUE TITLE
IBM developer improving the nmon Analyser article

### ISSUE THREAD

**Issue by nigelargriffiths** [IBM/developer#176]
I would like to get that "nmon Analyser" page updated or removed. at  https://developer.ibm.com/articles/au-nmon_analyser/ 
Your Call on the action.

If updated the main points are:

Change
By Stephen Atkins
to
Original article by Stephen Atkins

Change 
Updated April 19, 2006 | Published November 15, 2003 
to 
Updated Jan 13 2020 | Published November 15, 2003 

Delete 
The tool currently comes in the form of a spreadsheet for use with Microsoft® Excel™ 2000 or later. 

Delete
To place your name on the e-mail list for updates, contact Stephen Atkins. 

Delete
New features
The new features for the nmon_analyser tool now include:
Support for AIX® 5.3 and micro-partitions (NMON10)
Support for input files with greater than 65K lines
Improved graph sizing and positioning
Option to specify which sheets are analysed
Support for printing — with automated pagination
Automated Web publishing — in PNG or GIF formats

Change
The tool is distributed as a .zip file and contains .xls files 
to
The tool is distributed as a .zip file and contains .xlsm files 

Change
You can download nmon analyser from the IBM Wiki at nmon Analyser.    <- this refers to the old Developerworks download that I change to refer to the URL below but its a mess and scheduled for removal
to
You can download nmon analyser from the IBM Wiki at http://nmon.sourceforge.net/pmwiki.php?n=Site.Nmon-Analyser 

cheers, Nigel Griffiths

**Comment by mcorbin-ibm** [comment]
Thanks for the feedback and providing updates to make.  Updates have been made to the content.
