### ISSUE TITLE
[IBM Coders] "Sign out" doesn't appear to actually sign me out.

### ISSUE THREAD

**Issue by ShapeShifter499** [IBM/developer#18]
I'm using Arch Linux, both Firefox and Chromium have this issue for me.  Trying to click "sign out" doesn't seem to sign out my account. I don't have any extensions enabled in the Chromuim browser.

**Comment by johnwalicki** [comment]
Maybe you could clear *.ibm.com cookies or use a private browser window?

**Comment by ShapeShifter499** [comment]
Using a private tab, incognito mode, works here as a temporary workaround.
