### ISSUE TITLE
SQL PL tracing procedure article is not longer avaible

### ISSUE THREAD

**Issue by angoca** [IBM/developer#185]
The link to the article:

    http://www.ibm.com/developerworks/db2/library/techarticle/dm-0409rielau/

Is not longer available and it was included in several courses about how to develop Stored Procedures in Db2. That article included a set of files to instal sqlpltrc in the database, in Windows, Linux and the source code.

This tool should still be available for download, and the associated article

**Comment by mcorbin-ibm** [comment]
@angoca I have republished the article for now (https://www.ibm.com/developerworks/data/library/techarticle/dm-0409rielau/), but the downloads do not seem to be available from it.  I was able to download the files, and I have attached a ZIP file of them here for your use for now.

[dm-0409rielau-downloads.zip](https://github.com/IBM/developer/files/4214132/dm-0409rielau-downloads.zip)

----

Can you please share with us the URLs for the courses that refer to this article?  We will need to work with those course owners/authors to update the link to/use of this article.

**Comment by angoca** [comment]
The CF71 course was one of them. But this was a real, not virtual course.
Thank you for the sources.

**Comment by mcorbin-ibm** [comment]
Ok, thanks for the information.
