### ISSUE TITLE
Lost access to developer.ibm.com/linuxone as admin

### ISSUE THREAD

**Issue by bgilkes** [IBM/developer#188]
I am the lead architect for the LinuxONE Community Cloud.  I have been updating our LinuxONE Community Cloud web content via the developer.ibm.com/linuxone url with admin access for years to update the pages within using the online wordpress.  Today when I logged in with my IBM ID (bgilkes@us.ibm.com) to check on a bad link I noticed that I am a standard user and can no longer update the pages.  It appears that I am a standard or public user and the website is read only to me.   We have 500-1000 users at any time that use the Community Cloud showcasing LinuxONE and I have lost control of the web content.  Please advise.

**Comment by mcorbin-ibm** [comment]
Thank you for your question. Since this is an IBM-internal administrative matter, I have contacted you through internal channels.
