### ISSUE TITLE
Requesting Assistance for installing Wordpress plug-in on Mainframe Dev site

### ISSUE THREAD

**Issue by chrishoina** [IBM/developer#189]
Hello,

I can't seem to find anybody that can assist with installing a podcast plug-in on the Wordpress site that we have.  We don't have permissions to do this, so I was hoping to coordinate with somebody who could help us out.  

Thanks,

Chris

**Comment by mcorbin-ibm** [comment]
Thank you for your question. Since this is an IBM-internal administrative matter, I have contacted you through internal channels.
