### ISSUE TITLE
Cannot delete uploaded images from developerWorks recipe

### ISSUE THREAD

**Issue by GrahamHannington** [IBM/developer#19]
This issue duplicates my [post](https://www.ibm.com/developerworks/community/forums/html/threadTopic?id=56619dd6-b4e0-408c-b756-c9199ef27473) on 17 September 2018 to the IBM Community "Using developerWorks" forum:

> The Images dialog box in the recipe editor shows a "trashcan" icon next to each thumbnail. However, clicking that icon does not delete the image.
>
> In latest Chrome (on Windows 10), clicking that icon results in an error 403 (Forbidden: you don't have permission to access /index.php on this server).
>
> Which, curiously, is different from the error 501 (Not Implemented) that I used to get (the previous time I checked, several weeks ago).

I've had no response to that post, so I thought I'd try here.

Here's the "trashcan" icon:

![image](https://user-images.githubusercontent.com/8519708/49429883-8d774780-f7a1-11e8-8a52-092394e2d7eb.png)

And here's what the console of my browser (latest Chrome on Windows 10) shows when I click the trashcan:

![image](https://user-images.githubusercontent.com/8519708/49430083-01195480-f7a2-11e8-8aab-40f431ef16c5.png)

This issue exacerbates a separate but related issue: I can't update an uploaded image. More specifically: if I upload an image that has the same file name as an image I've already uploaded, then rather than replacing the earlier image, the recipe editor adds a new image with `-1` appended to the image file name.

So, if I upload an image, and later decide I want to update it, I upload the updated image, change the corresponding `<img>` element to refer to the `-1` file name, and live with the fact that the old image is still there.

**Comment by LindaMeyer** [comment]
Hi Graham,
Apologies for the delay in getting back to you here. I saw your comment and forwarded it to the development team. They are looking into it. 

I appreciate all of your feedback and am sorry that you are running into issues. We understand there is room for improvement in the recipes platform.  However, since we are working to provide a more robust platform to enable publishing on our site, we are now making limited tweaks to this existing platform. Our reason for this is to get you the best solution as quickly as possible.

Feel free to directly mention me for any other comment/question regarding recipes. I'm now following issues here so I should see them right away anyway. 

Thanks again for your time to send us this feedback and for your patience.
-- Linda

**Comment by GrahamHannington** [comment]
Hi @LindaMeyer,

Thanks for commenting here.

You wrote:

> Feel free to directly mention me for any other comment/question regarding recipes

I've taken you up on that offer (thanks!) and mentioned you in a comment on issue #21.

Re:

> we are working to provide a more robust platform to enable publishing on our site, we are now making limited tweaks to this existing platform.

Fair enough. Sounds good.

I'm grateful for the opportunity that dW recipes offers to publish content directly without intervention. But, yeah, there are some nits in the editor and formatting. And, although the "step-by-step" structure makes perfect sense for a recipe, I'd appreciate the opportunity to directly publish other types of content, such as articles, with less-prescriptive structures.

One aspect of the recipe editor that I like, and hope you'll keep in future authoring environments on IBM Developer, is the source code view. I find this useful in two ways:
* So that I can tweak the HTML (for example, as described in issue #21).
* As an offline backup. Sometimes, I'll work on a draft recipe over several days. And sometimes, when I return to a recipe editor browser tab that has been open for a while, and edit the recipe text, and then attempt to preview the recipe, the editor hangs with a "Creating recipe body..." message. I guess that's because my session has expired. I've also experienced other situations (that I have not been able to reliably reproduce) where the recipe editor hangs. So, when I'm editing a recipe in my browser, I keep a desktop text editor window open, and copy the source code into that. Here's a directory listing of the "offline" copy of my latest recipe:
```
metadata.txt
Ingredients.html
Step 1 - Activate the IMS Connect Extensions publisher API.html
Step 2 - Create a Splunk TCP data input.html
Step 3 - Start a feed job.html
Step 4 - Analyze the data in Splunk.html
graphics\
```
