### ISSUE TITLE
Code blocks in recipes require <br> for line breaks

### ISSUE THREAD

**Issue by GrahamHannington** [IBM/developer#21]
I want to present code blocks in an IBM developerWorks recipe.

I've used the recipe editor's one-and-only "template" to insert a code block. That inserted a `<pre>` element. I was surprised by that. I was expecting, [as recommended by the W3C](https://www.w3.org/TR/html5/grouping-content.html#example-666bcced) and elsewhere, `<pre>` with a `<code>` child.

Next surprise, and the reason for this issue: although the recipe editor initially honors the line breaks in the code blocks, the preview of the published recipe _doesn't_. To get line breaks, I have to insert `<br>` elements. 

My first thought was that this formatting was introduced by bogus properties in your preview/final CSS that causes `<pre>` to dishonor white space. However, that's not the case. I know that because I've used my browser's developer tools to dynamically insert line breaks in a preview page, and those line breaks are honored. (There are formatting nits in your CSS, especially when I insert a `<code>` child into the `<pre>`,  but I'll move on for now.)

The problem is caused by how you (the developers of this recipe functionality) store the recipe HTML. I know that because, when I close the recipe editor, and then reopen the recipe for editing in a new browser tab, the line breaks that were in the `<pre>` have gone.

I'd like to ask you to fix your code, but I'm fearful of introducing unwanted additional line breaks in existing recipes that contain code blocks.

For now, I'll satisfy myself by grumbling about the issue here, and inserting `<br>` elements into `<pre>` elements with gritted teeth.

**Comment by GrahamHannington** [comment]
Related nit...

Some of my code blocks have a first line that ends with a right square bracket (`]`).

That triggers buggy behavior in the processing you're (clearly) doing to the HTML: in the preview, the first and second lines of such code blocks are concatenated. The line break—the explicit `<br />` element—is lost.

My current workaround is to insert a space after the `]` at the end of the line, before the `<br />` element.

For example, the following source code in the recipe editor:

```html
<h4>No space after line 1</h4>
<pre>[Line 1]<br />Line 2</pre>
<h4>With space after line 1</h4>
<pre>[Line 1] <br />Line 2</pre>
```

results in the following formatting when I preview the recipe:

![image](https://user-images.githubusercontent.com/8519708/49778060-2d315a00-fcfb-11e8-9313-8b8ccd92a8ea.png)

And I can see, by inspecting the underlying preview HTML, that there is no `<br>` element in the first code block.

I've tried using entity references (`&#91;` and `&#93;`) in the recipe source code instead of literal square bracket characters, but nope, the recipe editor is "smarter" than that; it converts those references back to literal characters (unlike, say, entity references for colons).

**Comment by GrahamHannington** [comment]
More nits...

Why, in the preview (/final) CSS, are you rendering `<code>` in, say, the Consolas font, rather than IBM Plex Mono?

From the "Computed" tab of Chrome developer tools for a `<code>` element in a recipe preview:

![image](https://user-images.githubusercontent.com/8519708/49783661-72ad5180-fd12-11e8-8ae5-3ba08ef8b82f.png)

and:

![image](https://user-images.githubusercontent.com/8519708/49783694-9375a700-fd12-11e8-955c-7b3d1222205a.png)

whereas, you _do_ render `<pre>` in IBM Plex Mono.

**Comment by GrahamHannington** [comment]
Perhaps I should create a separate issue regarding fonts in `<pre>` and `<code>`. I'll do that if requested, but since I've already added one comment here about fonts, and I only uncovered this discrepancy while looking into the main `<br>`-related topic of this issue, I'll continue...

To recap: in recipes, you have chosen to render inline code in some font other than IBM Plex Mono; you render `<pre>` in IBM Plex Mono; in your code "template" in the recipe editor, you have specified `<pre>` without a `<code>` child. The result: inline code and code blocks are rendered in different fonts. I don't like that inconsistency; it looks odd to me.

Also: you render inline code with a colored background, but not code blocks. That, too, looks odd to me.

As a workaround, to render inline code in the same font as code blocks, I've inserted a child `<code>` inside the `<pre>`. This introduces a formatting issue: the lines of code are "striped", as per the first code block shown below. So I've introduced a `style` attribute into the `<pre>` (that I'll have to add to every code block), which gives me the result shown in the second code block:

![image](https://user-images.githubusercontent.com/8519708/49784588-bd7c9880-fd15-11e8-9fd3-366b24cd8310.png)

Here's the tweaked `<pre>`:

```html
<pre style="background-color&#58; #f4f4f4; padding&#58; 5px; margin-bottom&#58; 15px;"><code> ... </code></pre>
```

I don't enjoy making these tweaks—among other reasons, it makes the formatting "brittle"—but I want my recipe to look good _now_. And having inline code formatted differently to code in blocks—different font, different background shading—does not look good to me.

If I could, I'd tweak the CSS directly, but the recipe silently culls `<script>` elements (fair enough), so I can't use JavaScript to inject new CSS, which pretty much just leaves me adding `style` attributes to each element. I'd prefer to render inline code and code blocks in IBM Plex Mono, but I baulk at adding an attribute to every `<code>` element to achieve that.

**Comment by GrahamHannington** [comment]
Newly published recipe with examples of style-tweaked `<pre>` elements with `<code>` child: "[Forwarding a live feed of IMS Connect events to Splunk](https://developer.ibm.com/recipes/tutorials/forwarding-a-live-feed-of-ims-connect-events-to-splunk/)".

**Comment by GrahamHannington** [comment]
@LindaMeyer,

In issue #19, you wrote:

> Feel free to directly mention me for any other comment/question regarding recipes. 

so I thought I'd do that here (thanks!).

To recap my activity on this issue:

* I opened this issue because I noticed that code blocks in recipes require a `<br>` element for line breaks. This is, at best, highly unusual: according to convention (if you say I should have written "the HTML standard", I'll agree with you), `<pre>` elements should honor line breaks.
* I noticed that a right square bracket character (`]`) at the end of a line in a code block "breaks" the line-breaking behavior.
* I noticed that the recipe editor doesn't use the standard (er, conventional) `<pre><code>` markup for code blocks; just `<pre>`.
* I noticed that the final/preview recipe CSS uses different fonts for inline code (`<code>`) and code blocks (`<pre>`).
* I described my workaround: inserting a `<code>` child element and a `style` attribute into each `<pre>`.

The issues I met here are all just nits, but I'm surprised by how many there are: I would have thought that  enough recipes had been published, with enough examples of inline code and code blocks, for these issues to have been noticed and fixed earlier.

**Comment by LindaMeyer** [comment]
Thanks for this additional input @GrahamHannington. This is very helpful. And thanks for the direct mention. It does help me see your comments.

Your recipe looks great! You did a nice job of working around all of the coding issues. Apologies again that it wasn't easier. We will take all of this input into account on the new solution.

**Comment by GrahamHannington** [comment]
@LindaMeyer,

Thanks for the kind feedback.

### The recipe editor developers didn't think recipes would include inline code?

I forgot to mention this earlier: the formatting options offered by the recipe editor toolbar don't include inline code.   That's an odd oversight for an editor for "(software) developer" recipes.

To markup inline code—to semantically tag inline code with a `<code>` element so that it renders in a `monospaced` font—you need to use the "source code" view of the recipe editor. I use that source code view almost exclusively anyway, which is why I forgot to mention this omission earlier.

### To shade or not to shade?

To shade or not to shade inline code and code blocks on web pages is a question that IBM has answered in different ways on different sites:

* Recipes on the IBM Developer site shade inline code (if you can be bothered marking it up in the source code view with `<code>`) but not code blocks (`<pre>` elements without a `<code>` child).
* Topics in IBM Knowledge Center _do not_ shade inline code (`<samp class="ph codeph">`: I'd like to have a chat with whoever designed the IDWB DITA-to-HTML transform, and introduce them to the HTML `<code>` element 😄 ), but _do_ shade code blocks!

Being small-minded, I'd prefer some consistency in this formatting.

My experience is that websites outside of ibm.com tend to shade both inline code and code blocks.

I waver between whether or not to shade either or both. Functionally, I wonder whether shading inline code affects comprehension speed. Aesthetically, too many shaded inline code snippets can make a paragraph look like it's got a nasty rash. These concerns aside, shading _is_ useful to clearly distinguish `inline code` from plain English; sometimes, a monospaced font by itself is too subtle to clearly indicate this.

**Comment by GrahamHannington** [comment]
@LindaMeyer 

You wrote:

> We will take all of this input into account on the new solution.

Thanks! On that note, and also on the subject of presenting code on IBM Developer, if you want to bring the presentation level up a notch (on par with other websites): **please consider introducing support for code syntax highlighting**.

For example, I've published [documentation on GitHub](https://fundisoftware.github.io/taw-sample-dashboards-jcl/#topic=jcl-cmf-6e13.html) that uses the [Prism](https://prismjs.com/) syntax highlighter with a language definition I created for z/OS JCL. (I keep meaning to polish this definition and submit it to the Prism project.)
