### ISSUE TITLE
Advocates site doesn't show content

### ISSUE THREAD

**Issue by sdaschner** [IBM/developer#22]
The Advocates sites don't show any content: https://developer.ibm.com/code/community/advocates/ and https://developer.ibm.com/community/advocates/

**Comment by neilmack** [comment]
@sdaschner Sebastian, thank you for your comment and apologies for the delay in responding. We are making multiple updates to IBM Developer that will improve the look, response times, and content available. While this refresh is happening, there will be some areas that are a bit rough around the edges, and you've found one of them. We'll have a new advocates page in place as soon as possible. Thank you again for highlighting this issue.
