### ISSUE TITLE
Need edit access to: https://www.ibm.com/developerworks/downloads/r/architect/

### ISSUE THREAD

**Issue by psmith2016** [IBM/developer#24]
Please add:

Martin Axelsson <martin.axelsson@hcl.com>
To: Kimi Cousins <kimi.cousins@hcl.com>, "Keiran Lunney (IBM - New Rich B)" <KLunney@uk.ibm.com>, Phyllis A Smith <phylliss@us.ibm.com>, "rlb@ca.ibm.com" <rlb@ca.ibm.com>

as editors of:

https://www.ibm.com/developerworks/downloads/r/architect/

Also pursuing through email request.

Thank you!

**Comment by mcorbin-ibm** [comment]
Sarah Domina will reach out to you via email to work with you on getting the trial/download updated.
