### ISSUE TITLE
access Forbidden due to Akamai CDN.

### ISSUE THREAD

**Issue by amoriba** [IBM/developer#25]
My workstation can't access to https://developer.ibm.com/javasdk/downloads/sdk8/.
![image](https://user-images.githubusercontent.com/7568509/50131410-59357800-02c5-11e9-8d8d-b7843cc4953b.png)

This issue happen to my primary workstation and some of my colleague in same branch office.
Invalid response can't be solved by clearing cache of browser. All browser got same 403 response from server even if using curl command. This situation would be continuing for several days.

![image](https://user-images.githubusercontent.com/7568509/50131427-6e120b80-02c5-11e9-9189-5a00d3fd9011.png)

$ curl -I -s -X GET https://developer.ibm.com/javasdk/downloads/sdk8/
HTTP/2 403
content-encoding: gzip
content-length: 269
content-type: text/html; charset=iso-8859-1
date: Tue, 18 Dec 2018 04:10:08 GMT
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
content-security-policy: upgrade-insecure-requests
strict-transport-security: max-age=31536000

It is my knowledge that our available current work-around is using proxy or VPN/VTS to change client IP address. It seems like Akamai CDN service is working wrongly somehow.
We encounters this issuer multiple times and this is famous, however it block our business.

**Comment by neilmack** [comment]
Thank you for your query. We have not seen any other similar issues but we will refer your question to an administrator to ensure that everything is working as designed.

**Comment by amoriba** [comment]
Hi,
Today, I have same issue. My colleague in same branch office doesn't have this issue.
Let me know how to solve this issue.

**Comment by neilmack** [comment]
Akira, sorry to hear you're still having issues. I've referred your question to our tech team and they will follow up with you.

**Comment by leahket** [comment]
@amoriba just to clarify you are trying to access from Japan (not China)  and you (and your colleague) are blocked from the actual downloads page:  https://developer.ibm.com/javasdk/downloads/sdk8/

**Comment by amoriba** [comment]
@leahket  Obviously, we are trying to access from Japan. Today, I can access all pages somehow. However my colleague in same office building are blocked (status code 403) from the actual downloads page you indicated.  He can't access following 4 hyperlink too. We had been encountered this intermittent issue for 1-2 years on an intermittent basis. The situation kept for several days and affected client PC are changing as situation going on.  (of course, we know this situation could be bypassed by using proxy or VTS  as temporary solution. But it is not solution for this unknown issue's root cause.)

![image](https://user-images.githubusercontent.com/7568509/51515018-61994980-1e55-11e9-91d1-909d94c05dce.png)

**Comment by leahket** [comment]
I have had a similar problem before,  where an individual sitting right beside me can open a page that gives me an error and this is because we were being routed through different external servers to obtain the page source.  I will investigate the issue with another group, and if they have any suggestions or explanations, I'll post here.

**Comment by neilmack** [comment]
Akira, closing this issue as I believe you have worked with our engineering team and the problem that was specific to your location is resolved.

**Comment by amoriba** [comment]
Definitely yes. Our issue is solved.  Thank you.
