### ISSUE TITLE
Poor quality of the specialisation content and delivery at Coursera

### ISSUE THREAD

**Issue by diggiespace** [IBM/developer#26]
Please pay attention to this request. I believe this should be crucial for you as potentially when students are not happy with the learning material they will just switch to another provider such as GCP, AWS or Azure. I'm talking about **Advanced Data Science with IBM** specialisation delivered by Romeo.  Also note that **the way these courses are delivered has impact on the IBM brand.** 

**Issue:** 
Courses are not thought through and you feel they were created just for the sake of being out there. Starting from description of the courses (not complete info) and ending by formulation of assignments. Major issue here is that teaching is not for everyone. A good tutor/teacher always thinks from the perspective of a student, understands that people have different knowledge background and tries to tailor the content to the wide masses. Content should be presented so that it's easy to follow, understand and learn from. It's significant **to teach** _not just to show saying repeat after me._  Logic should be always there.

**Proof:**
For example check discussions of the Scalable Data Science course which is a part of the specialisation. You'll find many confused students complaining that the curse is difficult to follow. They encounter multiple errors and even mention that delivery of the course should be revised. People notify that they learn from many sources but this course delivered poorly. Also, check this page (https://github.com/IBM/coursera/wiki/FAQ) to see more issue but this is really nothing comparatively to discussions.  

**More than that:**
Check answers of the tutor (Romeo). They are all short and without thorough explanation. A good teacher/tutor always says WHY smth happens, what happens next and again WHY we need all of that. This is a vague example but you should get the point. Currently it feels like all the content is delivered in the way that it's clear for Romeo what's going on and that's enough. Students will find their way. 

This is disrespectful, especially for people who pay money for these courses. I'm still on my free month as a gift from the Applied AI coder program but really will think if I should stay or come back to DataCamp, Udacity or eDX (Microsoft Specialisations).

**Comment by diggiespace** [comment]
I communicated it to the Coursera support team as well.

**Comment by diggiespace** [comment]
These are some of the links leading to the issues submitted by frustrated students:

1. https://www.coursera.org/learn/ds/programming/7Yp62/week-2-programming-assignment/discussions/threads/Szw87g2jEemZUwrw3z8SgA
2. https://www.coursera.org/learn/ds/programming/7Yp62/week-2-programming-assignment/discussions/threads/f1WHWr5REei47A7ax6s2UA
3. https://www.coursera.org/learn/ds/programming/7Yp62/week-2-programming-assignment/discussions/threads/N2dejwe_Eem9Aw6qWUc8Og
4. https://www.coursera.org/learn/ds/programming/7Yp62/week-2-programming-assignment/discussions/threads/RzycwwGKEemF-hL9108AEg

**Comment by diggiespace** [comment]
Keep browsing and you'll find much more

**Comment by neilmack** [comment]
Thank you for your comments. Note that this board is only for information pertaining to the IBM Developer website (https://developer.ibm.com/). We will forward your comments to the course owner.
