### ISSUE TITLE
DWAnswers wrong posted by userid in the email  

### ISSUE THREAD

**Issue by shashimara** [IBM/developer#27]
Reference : post 

https://developer.ibm.com/answers/questions/403799/was-9-application-fails-to-start-wtih-cdiruntimeex/

For the above post, I get an email indicating the post is from  "SergeiMalynovskyi"   which is not the case.  Looks like there is a problem with  userid related to the post 
--

Followign was the email : 

===========
A new answer to the question WAS 9.0 application start issue was posted by SergeiMalynovskyi:Check here - https://developer.ibm.com/answers/questions/403799/was-9-application-fails-to-start-wtih-cdiruntimeex/ View SergeiMalynovskyi's new answer
--
Thanks,				 				The IBM Community team				 				IBM Developer Answers

================

This is FYI to check on the email notification and email IDs !!

**Comment by neilmack** [comment]
Thank you for your feedback. The dWAnswers platform is undergoing extensive updates. We have alerted the technical team to your comments and the issue you're seeing.
