### ISSUE TITLE
developer.ibm.com account issue

### ISSUE THREAD

**Issue by rtreddy** [IBM/developer#28]
Hi, I am tech lead for IBM Directory Server product support. I used to respond to questions on developerWorks questions section related to our product. Now I am trying to respond to a query on this new question:
https://developer.ibm.com/answers/questions/486395/advantage-of-database-alias-in-tds.html?utm_campaign=answers&utm_medium=email&utm_source=answers-new-question&utm_content=answers-answer-question
I can see the question and contents of that page.
Then I click on "Sign In" on the top right corner. I use my ibm id "rtreddy@us.ibm.com" to login. 
Login is successful.
but the page from above url doesn't show up any more, instead it takes me to 
https://developer.ibm.com/answers/answers/users/logout.html
Page contents show the following. 
Page Not Found

The page you were trying to reach was not found in IBM Developer Answers. If you feel you're seeing this page in error, please contact the site administrators.

Please help in resolving this issue.  
I've tried this on different browsers, Safari, Chrome, Firefox and each results in the same.
Thanks in advance.
Ram (rtreddy@us.ibm.com)

**Comment by neilmack** [comment]
Hi Ram, thank you for your comments. The Developer Answers platform is undergoing numerous updates to resolve various issues. Please let me know via internal email if you're still experiencing issues.
