### ISSUE TITLE
Article on WAS security hardening needs a refresh

### ISSUE THREAD

**Issue by jtmulvey** [IBM/developer#29]
The article at this location needs to be refreshed with several corrections and I'd like to add a new section on WAS Liberty security hardening.  Who do I need to contact about this?

**Comment by jtmulvey** [comment]
The article I am referring to is here:
https://www.ibm.com/developerworks/websphere/techjournal/1303_lansche/1303_lansche.html

**Comment by neilmack** [comment]
@jtmulvey James, thanks for your question, we'll notify the editor for this content area. That editor will contact you and determine the best approach for presenting your new material.

**Comment by andrea-pichler** [comment]
@neilmack were you able to get in touch with the editor of this content area? Thank you!

**Comment by neilmack** [comment]
@andrea-pichler Andrea, yes! And @jtmulvey, James, my apologies for taking so long to get back to you. So, the main question is whether the original authors want to update the previous article, or whether you would like to create a new, current tutorial. Amy, our editor, recommends the following steps: 

1. James should contact the original authors (Martin Lansche and Keys Botzum) and see if they can agree on all the content changes.
2. James, Martin, and Keys can create a Word file with all the text of https://www.ibm.com/developerworks/websphere/techjournal/1303_lansche/1303_lansche.html, turn on track changes, and make the needed changes or additions and then send that document to Amy Reinholds (IBM editor).
3. Amy will update the existing document at https://www.ibm.com/developerworks/websphere/techjournal/1303_lansche/1303_lansche.html 
4. Alternatively, if James wants to create a new tutorial, he should submit a proposal for through our internal contribution form. (I'll send the link via email).

So, you have the option on the "how" but we will definitely work with you on publishing updated content. Thanks again for your question. You can contact me through Notes or here if you have further questions.
