### ISSUE TITLE
Please help, can not access issues to developer "Answers" section

### ISSUE THREAD

**Issue by sammofung** [IBM/developer#3]
Hi IBM Developer,

I have issues accessing the "Answers" section of developerworks. Is there something I need to sign up to, in order to get access?

Apologies if I am posting this in the wrong spot, but I could not find anywhere on your site where I can contact someone for help besides this github area. (Couldn't access the Answers section afterall).

Your help is much appreciated.

![image](https://user-images.githubusercontent.com/31976309/45398831-a8de2500-b680-11e8-9f12-3bcb9c6e0141.png)

**Comment by neilmack** [comment]
@sammofung Were you able to access? The page seems to be working as designed.

**Comment by sammofung** [comment]
Hi @neilmack I just tried it now and it seems to be working just fine. Apologies for the alarm, don't know what happened yesterday, but I will close this issue now. Thanks for your time.
