### ISSUE TITLE
Is it possible to migrate a user profile to a new email address?

### ISSUE THREAD

**Issue by bpatel71** [IBM/developer#30]
We have an IBMer who has transitioned to a development partner as part of the mission being moved from IBM to the partner company. The individual is/was a Developer Answers moderator and I'm wondering if it is possible to either migrate his previous ID profile across to his new email address, or failing that for him to create a new profile and have that bumped up to Moderator?

User profile: https://developer.ibm.com/answers/users/254647/clark-jackson/

**Comment by LindaMeyer** [comment]
I have forwarded your request to the person in charge of dW answers. I'll let you know when I hear back from him.

**Comment by jantley-ibm** [comment]
It is possible to transfer assets (reputation points, questions, answers, comments) from one profile to another; this is common with a change in employment status where the existing profile becomes unusable.  However, moderator privileges are reserved for IBM employees only.

**Comment by bpatel71** [comment]
Would moderator privileges be permitted for someone who has a user@iespc.ibm.com W3 ID? These are Partner Connect IDs used for limited access to IBM systems - think of them as restricted Contractor IDs.

**Comment by jantley-ibm** [comment]
Yes.  Contact me directly with pertinent user information.
