### ISSUE TITLE
Error downloading ibm portal images on docker

### ISSUE THREAD

**Issue by taibc** [IBM/developer#31]
Hi,

I am trying to download the image ibm portal by using below command

docker pull ibmcom/websphere-portal

It downloaded 10.25GB successfully. But when extracting, it got an error: No space left 

My RAM size is: 8GB, 

How can I fix this error ?

Many thanks !
Tai

**Comment by taibc** [comment]
Please see the detail of log 

> $ docker pull ibmcom/websphere-portal
> Using default tag: latest
> latest: Pulling from ibmcom/websphere-portal
> 256b176beaff: Pull complete
> 0f544f32d942: Extracting  10.25GB/10.25GB
> fe1f9d227767: Download complete
> failed to register layer: Error processing tar file(exit status 1): write /opt/I
> BM/WebSphere/PortalServer/bp/wp.utl/unifiedtasklist/installableApps/unifiedtaskl
> ist.war: no space left on device

And this is the machine's info

> docker@default:~$ df -h
> Filesystem                Size      Used Available Use% Mounted on
> tmpfs                   890.4M    229.1M    661.3M  26% /
> tmpfs                   494.7M         0    494.7M   0% /dev/shm
> /dev/sda1                17.8G     46.1M     16.9G   0% /mnt/sda1
> cgroup                  494.7M         0    494.7M   0% /sys/fs/cgroup
> /c/Users                 78.5G     76.1G      2.4G  97% /c/Users
> /dev/sda1                17.8G     46.1M     16.9G   0% /mnt/sda1/var/lib/docker
>

**Comment by neilmack** [comment]
Tai, thank you for your comments. This repo is designed to handle feedback about the IBM Developer website (https://developer.ibm.com). If there's no support link on the page you're working on, you can send your query to IBM Support (https://www.ibm.com/support/home/), who can direct you from there.
