### ISSUE TITLE
Alignment off on boxes(cards) in events pages when long strings are present

### ISSUE THREAD

**Issue by chupman** [IBM/developer#33]
When I look at [https://developer.ibm.com/events/page/2](https://developer.ibm.com/events/page/2) instead of 2 rows of 4 cards, I'm seeing 3 on the first row, 1 on the second and 4 on the last.

Possible fix would either be a check for max length on a word in the title, max width on the card or input validation.

**Comment by neilmack** [comment]
@chupman Thanks very much for your comment! We've relayed to our tech team.

**Comment by krook** [comment]
@neilmack, In this case, it looks like because there's no space in the long string "Machine Learning~Bhub:Trivandrum" it's pushing the width of that first tile.

**Comment by chupman** [comment]
Yup. it's happening on pages 5 and 9 as well. Short term fix would be to just clean the data.
