### ISSUE TITLE
Bug?:  IBM API Connect: Workflow and lifecycle management course content is neverending redirect loop

### ISSUE THREAD

**Issue by mikkokallioibm** [IBM/developer#37]
Hello, 

I was just notified that one of the training courses on developerWorks is currently in a non usable state. API Connect: Workflow and lifecycle management (https://developer.ibm.com/courses-center/all/ibm-api-connect-workflow-and-lifecycle-management/) course keeps on refreshing the page which makes it impossible to try to watch the video content or look at the lab steps. Could someone please look into this?

**Comment by neilmack** [comment]
@mikkokallioibm Hi Mikko, thanks very much for your note. We've referred the issue to our support team and they are investigating. As you might be aware, we are currently updating much of the IBM Developer content and infrastructure. You could encounter some occasional problems as we complete this work. We do apologize and regret the inconvenience, but we're confident the end result will be a more valuable, usable site. Thanks again for letting us know about this page.

**Comment by raghav2650** [comment]
Same issue for me as well, unable to take course and this issue exists from more than a month. 
Please resolve ASAP and update us.
IBM API Connect Workflow Management (https://developer.ibm.com/courses/all-courses/api-connect-workflow-and-lifecycle-management/)

**Comment by mcorbin-ibm** [comment]
@raghav2650 @mikkokallioibm Try going here:

https://developer.ibm.com/courses-center/all/ibm-api-connect-workflow-and-lifecycle-management/

**Comment by mikkokallioibm** [comment]
Seems to be working now! Thank you so much.
