### ISSUE TITLE
SCaLe issue - listed at Sao Paulo

### ISSUE THREAD

**Issue by wendigo-code** [IBM/developer#39]
I was logging into Developer.ibm.com to attempt to contact someone at ibm regarding SCaLe and had a VERY difficult time finding it, and then when i did, it was listed as Sao Paulo?

What the heck... I have been going to SCaLe for years... and i know its in Pasadena still, come on IBM, lets do this....

**Comment by neilmack** [comment]
Thank you very much for your note. We'll alert the content owner about the error on the event page.

**Comment by neilmack** [comment]
Reader highlighted issue with location tagging, since fixed. Closing.
