### ISSUE TITLE
Link to "Go deeper with IBM Cloud and get Certified" from the recommended section of the "IBM Cloud Essentials" badge on youracclaim is broken

### ISSUE THREAD

**Issue by elamocaibm** [IBM/developer#4]
After earning the "IBM Cloud Essentials" badge on youracclaim.com, clicking on it brings up the details page for the badge and, on the right-side, a recommended section. Amongst the recommended actions, there is a "Go deeper with IBM Cloud and get Certified" with a link as such: https://www.youracclaim.com/badges/9d44fbf9-91a6-4640-a0cf-9021d32d3492/recommendations/5e3d2c55-2370-4d2c-bfbe-9d5289914b07
That link is broken and points to the error page of the developer website.

**Comment by neilmack** [comment]
Thanks for letting us know, @elamocaibm, we'll try to get the link updated asap.
