### ISSUE TITLE
link to Data Science Experience portal

### ISSUE THREAD

**Issue by barca108** [IBM/developer#40]
Hello, I've started the course "Streaming analytics basics for Python developers", but can't reach the DSX portal anyhow. The link provided in the video directs me to the Watson studio, from there I can't find the way how to get to the IBM Data Science Experience.  Do I have a wrong link? Or is it somehow restricted? If so, where can I request for access? 
Many thanks for the answer ;)
Bara

**Comment by neilmack** [comment]
Hi @barca108, thank you for your comment. You don't have the wrong link -- the IBM Data Science Experience has actually evolved and has now been renamed "IBM Watson Studio."  So, when you click the link in the course it redirects to the Watson Studio page. On that page, if you click the "Start on cloud for free" button, you can create an IBM Cloud account and use the free version of Watson Studio for your course work. 

We have now added a note on the Overview and Prerequisites pages of the course to describe this name change. We regret any inconvenience this situation might have caused for you, and we hope the new note will clarify the situation for you and other interested developers. Thank you again for alerting us -- and good luck with the course!

**Comment by barca108** [comment]
hi @neilmack, many thanks for your investigations and advice!!! Have a great weekend! ;)
