### ISSUE TITLE
Unable to execute your request

### ISSUE THREAD

**Issue by ErwanLeBras** [IBM/developer#41]
Every time I try to enter a new question in DWanswer, I get:

**Unable to execute your request**
_We're sorry, but we're unable to execute your request. You are probably seeing this error because your session expired due to inactivity. When using IBM Developer Answers, constructing your posts offline and then posting them in a timely fashion once on the site should prevent inadvertent loss of data. Please attempt to visit the homepage of this site and then try your action again. If you believe this error is incorrect, please contact the site administrator(s)._

This error is definitely incorrect. 
I did re-login in an other browser, copy-paste my question and got the same error... Less than 30 sec after login so definitely not inactivity or expiration...

**Comment by neilmack** [comment]
@ErwanLeBras Thanks very much for your query. We'll refer to out support team to follow up and will post more info as soon as it's available.

**Comment by LindaMeyer** [comment]
@ErwanLeBras Our support team recommended the following:

In instances where logging out and back in are not successful, try using a private browser session and then logging in, or clearing ibm.com cookies and then logging in.

**Comment by ErwanLeBras** [comment]
Hi Linda,

It does not work.
For instance, I run a private window.
I clear the cookies.




I connect to https://developer.ibm.com/answers/index.html

I login and click on the blueworks live tab:




Click on the "Ask a question" and  enter my stuff.
Then click on the "Post your question":

I can see the "Sending request to developer.ibm.com"
then
"Waiting for developer.ibm.com"


and then Access Denied




I've been trying with Safari, with IE, with Firefox...
I have tried on two different machine...
So I don't think the issue is on my side, but more on the Developer works
side.


Yours,

Erwan

**Comment by LindaMeyer** [comment]
@ErwanLeBras Hi Erwan, I see you have posted your problem on another issue. This is great! I was going to get you in touch with Jeff. I see he already posted a response to you there (https://github.com/IBM/developer/issues/44) so we should close this one. 

@neilmack Would you close this?

**Comment by neilmack** [comment]
Closing this issue as the discussion/ is consolidated in #44.
