### ISSUE TITLE
Code Challenge 2019 - broken link

### ISSUE THREAD

**Issue by elsandkls** [IBM/developer#42]
On the code challenge for 2019, the link to the blog in the first part of the challenge is broken. 
https://ibmcoders.influitive.com/challenges

The blog that it's trying to link to is here:
https://developer.ibm.com/blogs/2019/02/12/code-and-response-puts-top-coding-challenge-winners-to-work-saving-lives/

**Comment by krook** [comment]
Thanks for the report @elsandkls! I'll let Ron Wen know so he can update the challenge link.

**Comment by krook** [comment]
Fixed. Thanks again @elsandkls
