### ISSUE TITLE
Spring boot 2.1.2 issue with websphere application server 8.5.5.14 

### ISSUE THREAD

**Issue by pikuit** [IBM/developer#43]
I am trying to deploy spring boot webapp with spring-boot version 2.1.2.RELEASE in Websphere Application Server 8.5.5.14 but receiving error. 
Have added shared library refresnce to the application war file and saved it with class loading parent first . Yet the  issue nt yet resolved. PLease help on the same.
ISsue:
java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider org.springframework.web.SpringServletContainerInitializer not a subtype

**Comment by LindaMeyer** [comment]
@pikuit Sorry, but I'm unable to help you with this question. However, I can point you to a place where you might be able to find an answer. It is called IBM Developer Answers.
https://developer.ibm.com/answers

**Comment by pikuit** [comment]
Hi Linda,

I tried posting the question in the below mentioned site I.e. ibn develope
ask question but got error unable to process the request.. from there it
was mentioned to put up question in github

Please let me know how to proceed with the question

Regards,
Priyanka

**Comment by LindaMeyer** [comment]
@jantley-ibm Jeff, Can you help this user with an IBM Developer Answers problem?

**Comment by jantley-ibm** [comment]
Hi pikuit, please provide a link to your profile page on Answers and I'll look into the problem.

**Comment by pikuit** [comment]
Hi Jeff,

sorry for delayed response. 
My profile link: https://developer.ibm.com/answers/users/411194/kristen19/

**Comment by jantley-ibm** [comment]
It looks like you were able to post successfully earlier today.  If you have further problems, let me know.

**Comment by pikuit** [comment]
Thanks jeff. After sharing you the link , miraculously able to post :)
has there been any update to site which is now allowing me to post

**Comment by neilmack** [comment]
Closing this issue as the original is resolved and no further similar issues reported.
