### ISSUE TITLE
Can't get passed the Login popup while accessing IBM Developer Courses

### ISSUE THREAD

**Issue by nibrasohin** [IBM/developer#45]
![image](https://user-images.githubusercontent.com/16845327/53269100-fe017680-36b5-11e9-9e71-4b1be8276937.png)

After logging in using the w3 ID lands on this page showed in the image. After clicking on login it just refreshes the page and lands back on the same page. Can't get pass through it. Tried different browsers including incognito modes.
Link to the developer courses: https://developer.ibm.com/courses-center/
Note: My w3 account was re-enabled after coming back as full time from being a co-op.

**Comment by LindaMeyer** [comment]
@nibrasohin I'm sorry to hear about the problem you are having logging into our courses on IBM Developer. 

@silveyram Manny, Can you help or forward to someone who can? Thanks!

**Comment by ahmedmfarahat** [comment]
Hi I have the same issue since last year while logging in using my w3 id, I need help very urgent, It's very annoying that none of the support tickets I sent anyone replied back to them

**Comment by mcorbin-ibm** [comment]
@nibrasohin Can you share with us the specific course that you are trying to take and log in to?  Also, are you logging in with your IBM ID account information (which often is your w3 account, or at least sync'd with w3 via SSO)?  Can you share your IBM ID email with me privately?
  
@ahmedmfarahat If you can share the same information, that'd be great.  Can you share your IBM ID email with me privately?

**Comment by ahmedmfarahat** [comment]
@mcorbin-ibm Can you please send me ur name on bluepages to be able to send you my information. Thanks a lot

**Comment by mcorbin-ibm** [comment]
@ahmedmfarahat Can you try again?  We think we have fixed your IBM ID login?

**Comment by mcorbin-ibm** [comment]
@nibrasohin Can you also try again?  We think we have fixed your IBM ID login?

**Comment by nibrasohin** [comment]
@mcorbin-ibm my account now seems to be working. Thanks for the fix, highly appreciated!
