### ISSUE TITLE
Broken AIX Toolbox web pages

### ISSUE THREAD

**Issue by nigelargriffiths** [IBM/developer#46]
Here is the UR:
- https://www.ibm.com/developerworks/aix/library/aix-toolbox/alpha.html

This web page is broken, hangs the browser for minutes with 10% of the page loaded and eventually the browser times out.

This out hangs too
- https://www.ibm.com/developerworks/aix/library/aix-toolbox/date.html

Tried Chrome and Firefox = the same result

Been broken for half a day now.

![image](https://user-images.githubusercontent.com/48133721/53655347-d6775480-3c47-11e9-8e27-92f185894224.png)

Cheers Nigel Griffiths at IBM

**Comment by LindaMeyer** [comment]
@nigelargriffiths Hi Nigel. Sorry to hear that you are having problems with the site.  I just tried and both pages loaded right away. Are you still having trouble? Try clearing your cache, using another browser, or using a private window and see if any of those help. Let me know if that doesn't work.
