### ISSUE TITLE
Login not possible with gmail alias email 

### ISSUE THREAD

**Issue by Ejay-3D** [IBM/developer#47]
Hello, 

We have found the following issue when using IBM ID with aliases and trying log in on https://developer.ibm.com/ .

First let me explain and clarify what is an alias and how it is used as I have already report that issue over the phone but the personn I had didn't understand what we are trying to achieve here. 

Using google gmail you can create a mail box like : emmanuel@gmail.com .
Gmail allow to create alias that allow to have a different email but it will go the the main box previsouly created eg : 
emmanuel+ibm@gmail.com will be received in mailbox emmanuel@gmail.com.

We are doing this because we need multiple IBM ID when working for services in different compagny .
eg: emmanuel+socgen@gmail.com / emmanuel+ikea@gmail.com etc .... 
that prevent to create a new gmail account each time and to get everything in the same box. 

I already checked that the + sign is allowed on both ibm.com and developer.ibm.com.
There's NO issue to create account with alias on ibm.com or on developer.ibm.com. 

The issue is that when we create IBM ID account on IBM.com it is possible to login to IBM.com but it is impossible to login on developer.ibm.com. 
The behavior is pretty strange as their's no error message on developer.ibm.com. Once you enter your password and validate it the site just loop back to the login window.  

Why I think there is a bug ? 
If you create directly you IBM ID using alias from developer.ibm.com you are able to login with it in developer.ibm.com. 
You can then connect as well to IBM.com with the same. 
BUT 
If you log out from developer.ibm.com and try to log in again it is impossible to login.

Please try to reproduce the issue as described . 
1- Create a google account 
2- create an IBM ID with an alias from this google account .
3- Login to IBM.com with this ID. 
4- try to login to developer.ibm.com with this new IBM ID. 
5- at this step you should have the issue and not be able to login to developer.ibm.com while you can on any other IBM website. 

Could you please investigate this issue? 

Thank you ejay

**Comment by mcorbin-ibm** [comment]
Thank you for this very detailed explanation of the login issues you are facing.  
@silveyram I think you'll need to investigate and figure this one out?

**Comment by Ejay-3D** [comment]
Hello do you have any update for me on this issue ? 

Thank you .

**Comment by silveyram** [comment]
looking into this now

**Comment by silveyram** [comment]
@ejay-ibm we spent time looking into this and this shouldn't be an issue.

First of all, we currently do not have user login, so when you try and log in, it tries to pass you to the back end, and since you don't have access to the back end, you get the error.

How are you getting to the login in developer.ibm.com?

**Comment by Ejay-3D** [comment]
@silveyram 
Hi sorry for late reply : 

I login ( "sign in" ) from this page for example: https://developer.ibm.com/api/list

hope this helps . 

Ejay

**Comment by Ejay-3D** [comment]
Hello, 

Do you have any update to provide?

Thank you

**Comment by mcorbin-ibm** [comment]
@ejay-ibm Is this the only page where you have this issue, or are there other pages where you also have this error?

**Comment by Ejay-3D** [comment]
This is the only page I have tried, as it is a page I need to access from our application Watson supply chain insights.

**Comment by Ejay-3D** [comment]
@mcorbin-ibm @silveyram 
Have you tried to reproduce the issue yet ? 
Would you like to make a webex with me to demo the issue?
thanks 
Ejay

**Comment by Ejay-3D** [comment]
@mcorbin-ibm @silveyram 
Hi, 
Do you have any update for me? 
Would you like to do a remote session so I can demonstrate the issue? 

Thank you

**Comment by mcorbin-ibm** [comment]
@ejay-ibm We cannot help you.  We have forwarded this issue on to the API explorer team.  If you send me (Michelle Corbin) your IBM email address, I can copy you on that email exchange such that you can reach out to them directly.

**Comment by Ejay-3D** [comment]
@mcorbin-ibm Hi, 
Unfortunately, we will go nowhdere with this. 
 I started to investigate this issue with the API explorer team ( Case created and now closed ) And they said that it was not an API explorer issue. but a website / IBMID Issue.  
So I opened a ticket to the IBM ID team, and they said that it was not an IBM ID issue since the creation and login works ok. 
Then I finally created this git here to your team as the Login is an issue with the developer site. 

Have you try to reproduce the issue and debug it?

Thank you

**Comment by mcorbin-ibm** [comment]
@ejay-ibm Can you please send me (corbinm@us.ibm.com) your email address?

**Comment by mcorbin-ibm** [comment]
@ejay-ibm Can you please see if you can log in now?  A fix has been deployed!  :)

**Comment by Ejay-3D** [comment]
I tested and Indeed I can login now. 

I'm waiting for the end user confirmation that the issue is fully resolved and will update for closure once done . 

Thank you for all the help !

**Comment by Ejay-3D** [comment]
I confirm that the issue is resolved . 

Unfortunately, I discovered a new one where it's not possible to log out. ( with any accounts ( it is not related to alias ))

I'll raise a new git for this . 

Please close this one .
