### ISSUE TITLE
Cannot Log Into Cognos Forums Today

### ISSUE THREAD

**Issue by banarieo** [IBM/developer#48]
I have been using the Cognos Forums in Developerworks since they opened years ago. Today I am unable to log in. Cognos 10 Forum: https://www.ibm.com/developerworks/community/forums/html/forum?id=11111111-0000-0000-0000-000000002335 
After entering my username and password information, I get a page that says "We are checking your profile and service subscription", with an animated circle, but nothing after that. I've left this page open for 90 minutes hoping it will eventually resolve, but it does not.
I have cleared browser cache and restarted with no fix.
Ah, one more item: This failed to work with IE 11, but I just tried again with Chrome and it worked. So appears to be limited to IE.

Thanks.

**Comment by LindaMeyer** [comment]
@banarieo Thank you for taking the time to send us this feedback. I checked with our development team and they were aware of the issue. They just discovered it late last week, but are working on it. You are correct, it is specific to IE/Edge.

**Comment by neilmack** [comment]
Issue resolved.

**Comment by banarieo** [comment]
Thanks.

I noticed that the login now takes me to some directory, rather than
leaving me in the post I wanted to reply to. Is this the intended behavior?
