### ISSUE TITLE
Cannot submit a question to IBM Developer Answers

### ISSUE THREAD

**Issue by syseng1** [IBM/developer#51]
https://developer.ibm.com/answers/questions/ask/?topics=ilmt
I am logged in and my user name is displayed in the upper right side of the page.
I fill in the fields to ask a question and get a green check mark in the “I’m not a robot” box.  A minute or two after submitting the question,  I get the following error message:
“Sorry! developerWorks is offline
The developerWorks site is offline for a bit. Like you, we're eager to have the site back up.
We are working to restore service as soon as possible.”

**Comment by LindaMeyer** [comment]
@syseng1 Thanks for reporting this issue. I've contacted the support team. They are reviewing the logs to diagnose the issue. One thing you could try (if you haven't already) is to clear your cookies and cache and see if this issue persists. It's possible the maintenance page you saw was cached from earlier maintenance. Please let us know if that doesn't fix it.

**Comment by bostonhawk86** [comment]
I had that issue initially but I still can't submit a question.  I consistently get connection time-out errors.  I've tried with multiple browsers and multiple workstations and keep getting that same error.

**Comment by neilmack** [comment]
Issues with Answers have been reported as "resolved." Closing this issue but will reopen if problems re-occur
