### ISSUE TITLE
Blog / Tutorial content needs to be changed

### ISSUE THREAD

**Issue by HorstHummel** [IBM/developer#52]
Hi,

I got an issue with the following Tutorial https://developer.ibm.com/tutorials/hyper-protect-your-data/

I would also like to know, who published it and who did the change in Feb (was it me?)?
Thanks for getting back to me

**Comment by mcorbin-ibm** [comment]
Thanks for your feedback.  I have reached out to the editor who last updated the tutorial, and asked her to get in touch with you about the updates that you would like to propose.

**Comment by LinzSTP** [comment]
@HorstHummel I was asked to make some updates to your tutorial back in Feb by Matthew Cousens
Developer Advocate, IBM Z and IBM LinuxONE for Think2019.
[Tutorial - Quickly create a hyper-secure database.docx](https://github.com/IBM/developer/files/2993610/Tutorial.-.Quickly.create.a.hyper-secure.database.docx)
 I've attached his edits here for your reference. If you have additional updates, please contact me directly at lhalkire@us.ibm.com and copy John Swanson john.swanson@us.ibm.com Thanks.

**Comment by neilmack** [comment]
Reader is in touch with the editors re content. Closing.
