### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by stephan-volz** [IBM/developer#54]
Hi, following articles are no longer accessible due to some change done yesterday:

https://www.ibm.com/developerworks/library/mw-1702-volz-trs/1702-volz.html 
http://www.ibm.com/developerworks/bpm/bpmjournal/1509_volz1-trs/1509_volz1.html
http://www.ibm.com/developerworks/bpm/bpmjournal/1509_volz2-trs/1509_volz2.html

Please fix.

**Comment by mcorbin-ibm** [comment]
Responded via email.  @neilmack we can close this issue.
