### ISSUE TITLE
What happened to the Groovy tutorials?

### ISSUE THREAD

**Issue by mlzarathustra** [IBM/developer#56]
Until April 1st, IBM developer works used to have the best pages on Groovy. Where did they go? 

Please bring them back! 

thanks,
  -=miles=-

**Comment by mcorbin-ibm** [comment]
Thank you for taking the time to send us your comments. I'm sorry you weren't able to find a page you were looking for. 

Over the past year, we've been making several changes as we transition from developerWorks to IBM Developer. As part of that process, we are updating the site by removing old, outdated, or rarely visited pages. Our goal is to ensure that the content you find on our site is accurate, up-to-date, and relevant.  

Please let me know if there is anything else I can do to help you.
