### ISSUE TITLE
 Link to Viewlets example Templates guidelines not working

### ISSUE THREAD

**Issue by RMGood** [IBM/developer#57]
The following should be a useful link to show you how to create dashboard viewlets which would help me do my job, unfortunately it just lands me on a central page and the article cannnot be found.

https://www.ibm.com/developerworks/rational/library/10/createdashboardviewletsinrationalteamconcert

**Comment by mcorbin-ibm** [comment]
Thank you for taking the time to send us your comments. I'm sorry you weren't able to find a page you were looking for. 

Over the past year, we've been making several changes as we transition from developerWorks to IBM Developer. As part of that process, we are updating the site by removing old, outdated, or rarely visited pages. Our goal is to ensure that the content you find on our site is accurate, up-to-date, and relevant. 

Please let me know if there is anything else I can do to help you.
