### ISSUE TITLE
Unable to logout from : https://developer.ibm.com/api

### ISSUE THREAD

**Issue by Ejay-3D** [IBM/developer#62]
Once logged in to : https://developer.ibm.com/api 

The logout doesn't work : 

~~~~
https://developer.ibm.com/sso/logout?lang=en_US&d=https%3A%2F%2Fdeveloper.ibm.com%2Fapi%2Flist
~~~~

this is url which is executed when pressing logout but the redirect is not processed....

You just fall on a blank page. 

And calling again 
~~~~
`https://developer.ibm.com/api ` 
~~~~
you see that you are still logged in....

[developer.ibm.com.zip](https://github.com/IBM/developer/files/3058527/developer.ibm.com.zip)

Attaching network HAR file from inspect tools for deeper analysis . 

Thank you

**Comment by mcorbin-ibm** [comment]
@ejay-ibm Thanks for reporting this issue.  I have forwarded it along to the API explorer team to investigate.  Stay tuned.

**Comment by Ejay-3D** [comment]
@mcorbin-ibm Hello, did you get any feedback from the API explorer team ? 

Thank you !

**Comment by mcorbin-ibm** [comment]
@ejay-ibm I did not yet.  I sent another urgent message.

**Comment by Ejay-3D** [comment]
Hi @mcorbin-ibm Still no update from the API explorer team ? 
Thank you

**Comment by mcorbin-ibm** [comment]
After my last ping, I saw a request for folks to look into it, but nothing since.  I sent another ping, to nudge again.

**Comment by mcorbin-ibm** [comment]
@ejay-ibm I wanted to let you know that progress is being made on addressing this issue.  They've determined where/why it is happening, and now are working to figure out a fix for the issue.

**Comment by Ejay-3D** [comment]
Very good news! Thank you for the update.

**Comment by mcorbin-ibm** [comment]
@ejay-ibm The developers reported that they fixed the issue.  Can you try to see if it is now fixed for you?

**Comment by Ejay-3D** [comment]
@mcorbin-ibm Hi, Thank you! 
All works as expected now. 
Issue can be closed.
