### ISSUE TITLE
Broken link - Java/SSL

### ISSUE THREAD

**Issue by Mitchell21Nichols** [IBM/developer#64]
When we access,
Developer Technical Journal: JSSE/WAS
http://www.ibm.com/developerworks/websphere/techjournal/0502_benantar/0502_benantar.html

It's being re-directed to
https://developer.ibm.com/depmodels/hybrid/

Is there a way we can access the link again? It has useful information explaining how truststore search runs between Java and IBM product (WebSphere Application Server) layers.

**Comment by amy-reinholds-ibm** [comment]
Thank you for taking the time to send us your comments. I'm sorry you weren't able to find a page you were looking for.
Over the past year the IBM Developer team has been making several changes as we transition from developerWorks to IBM Developer. As part of that process, we are updating the site by removing old, outdated, or rarely visited pages, like the one from 2005 that you were looking for. Our goal is to ensure that the content you find on our site is accurate, up-to-date, and relevant.

Please let me know if there is anything else I can do to help you.

**Comment by Mitchell21Nichols** [comment]
Is there a way you can extract the context from that page for me? There is
one section from that page that I need to copy, most of my customers find
it useful... still useful today.

Regards,
Mitchell Nichols
IBM WebSphere Application Server Level 2 Support

**Comment by amy-reinholds-ibm** [comment]
Hi, @Mitchell21Nichols We can make a PDF file for you.  I will get one for you and attach it to this GitHub issue

**Comment by Mitchell21Nichols** [comment]
Yes, please. Thank you so much!

Regards,
Mitchell Nichols
IBM WebSphere Application Server Level 2 Support

**Comment by amy-reinholds-ibm** [comment]
@Mitchell21Nichols Here is the PDF file
[0502_benantar-pdf.pdf](https://github.com/IBM/developer/files/3061447/0502_benantar-pdf.pdf)

**Comment by amy-reinholds-ibm** [comment]
@mcorbin-ibm this is ready to be closed
