### ISSUE TITLE
Link broken to WebSphere Application Server Performance Tuning Toolkit (PTT)

### ISSUE THREAD

**Issue by FabioDP** [IBM/developer#67]
Link broken to WebSphere Application Server Performance Tuning Toolkit (PTT)
bad link in pdf doc published on 
https://www.ibm.com/developerworks/library/mw-1709-performtun/performtuning.html

should be https://www-01.ibm.com/marketing/iwm/iwm/web/dispatcher.do?source=swg-ptt
instead of https://www-01.ibm.com/marketing/iwm/iwm/web/download.do?source=swg-ptt&pageType=urx&S_PKG=ptt

**Comment by mcorbin-ibm** [comment]
Thanks for submitting your feedback.  This article was archived last fall, and carries the caveat about the PDF file:

> This content is no longer being updated or maintained. The full article is provided "as is" 
> in a PDF file. Given the rapid evolution of technology, some content, steps, or illustrations may 
> have changed.

**Comment by FabioDP** [comment]
I do understand that the article is provided "as is" but I regret that the 
links inside the pdf document, to download the tool, are broken.
Kind Regards
Fabio
