### ISSUE TITLE
Cannot access IBM Developer (I get Access Denied errors) from within secured institutional network

### ISSUE THREAD

**Issue by kusanagee** [IBM/developer#7]
Hey, IBM.

I intermittently can't load pages within developer.ibm.com when I'm logged into my institution's secured network; instead I get these errors:

> Access Denied
> You don't have permission to access "http://developer.ibm.com/answers/questions/413899/can-you-help-us-get-spss-to-work-with-mac-high-sie/" on this server.
> Reference #18.ac392b17.1536851211.20549a15
> 

I'm able to view pages from my phone network or from our institution's unsecured guest network. Is the issue on yours or our end?

I'm using Chrome Version 68.0.3440.106 (Official Build) (64-bit) and Firefox 62.0 (64-bit), on macOS High Sierra Version 10.13.6 (17G65).

Thanks!

**Comment by neilmack** [comment]
@kusanagee Thanks for your question and sorry you're having trouble. I've checked the link, plus the IBM Developer Answers home (https://developer.ibm.com/answers/index.html), on Mac and PC and I can't replicate your error from any browser. Perhaps a passing network issue or something on your end? Please try it again and let me know if you're still having trouble. In the meantime I'll check to see if there are any known issues with the page or with access from within a secure network.
