### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by bobturner1** [IBM/developer#70]
I am in the process of trying to cloud provision a Liberty server on z/OSMF and the link I was using just last Friday April 12th has gone
https://www.ibm.com/developerworks/library/mw-1704-wisniewski/index.html
Bob Turner

**Comment by amy-reinholds-ibm** [comment]
Hi, Bob. @bobturner1 
I'm sorry you were not able to find the information you were looking for. Over the past year, the IBM Developer team has been making several changes as we transition from developerWorks to IBM Developer. As part of that process, the team is updating the site by removing old, outdated, or rarely visited pages. Our goal is to ensure that the content you find on our site is accurate, up-to-date, and relevant.
This is one of the legacy developerWorks articles from 2017 that had low page views, and it was retired, and the URL was redirected to the IBM Developer landing page for hybrid cloud.

I'm going to attach a PDF file of the content:
[mw-1704-wisniewski-pdf.pdf](https://github.com/IBM/developer/files/3090719/mw-1704-wisniewski-pdf.pdf)

**Comment by bobturner1** [comment]
Thank you very much That is exactly what I was looking for.

Bob Turner

**Comment by neilmack** [comment]
Thanks, Bob and Amy. Closing this issue ...
