### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Mitchell21Nichols** [IBM/developer#71]
Need a PDF and source files from this broken link,
https://www.ibm.com/developerworks/websphere/techjournal/1210_lansche/1210_lansche.html

Thanks!

**Comment by amy-reinholds-ibm** [comment]
Over the past year, the IBM Developer team has been making several changes as we transition from developerWorks to IBM Developer. As part of that process, the team is updating the site by removing old, outdated, or rarely visited pages. Our goal is to ensure that the content you find on our site is accurate, up-to-date, and relevant.

This is one of the legacy articles from 2012 that had low page views, and it was retired, and the URL redirected to the IBM Developer landing page for hybrid cloud.

Mitchell reached out to me on email yesterday and I provided the PDF and source files:
[1210_lansche-pdf.pdf](https://github.com/IBM/developer/files/3090456/1210_lansche-pdf.pdf)


(In the future, an issue does not need to be opened at github.com/IBM/developer if I am contacted on email by an IBMer.)

**Comment by amy-reinholds-ibm** [comment]
@neilmack this issue can be closed

**Comment by neilmack** [comment]
Thanks Mitchell and Amy, closing ...
