### ISSUE TITLE
Pagination does not work with filtering on pattens catalog

### ISSUE THREAD

**Issue by mkistler** [IBM/developer#73]
From page:

https://developer.ibm.com/patterns/

I selected two filters: "Web development" and "Cloud"

This showed the first of supposedly 12 pages of results. But clicking on the right arrow to go to the next page gave the following message: 
```
Sorry, that page can’t be accessed or no longer exists
```

**Comment by mcorbin-ibm** [comment]
Thank you for the feedback.  We are investigating the issue.

**Comment by mcorbin-ibm** [comment]
@mkistler This issue has been resolved/addressed.
