### ISSUE TITLE
Typo in blockchain basics page

### ISSUE THREAD

**Issue by lewifr** [IBM/developer#74]
Hi just wanted to let you know there is a typo on page https://developer.ibm.com/tutorials/cl-blockchain-basics-intro-bluemix-trs/.

Chaincode (also called mart contracts)

should read:

Chaincode (also called smart contracts)

All the best,

Francis.

**Comment by mcorbin-ibm** [comment]
Thank you for submitting this feedback.  We have fixed the typo.
