### ISSUE TITLE
broken link dW article websphere/tutorials/1103_madgula/

### ISSUE THREAD

**Issue by henningburgmann** [IBM/developer#76]
The following developerWorks link is no longer available:
Managing failed flows using the Failed Event Manager API in WebSphere Process Server
https://www.ibm.com/developerworks/websphere/tutorials/1103_madgula/

Please, send the PDF version per mail (henning.burgmann@de.ibm.com) to me.

Thank you!

Kind regards
Henning Burgmann

**Comment by mcorbin-ibm** [comment]
Over the past year we have been making several changes as we transition from developerWorks to IBM Developer. As part of that process, we are updating the site by removing old, outdated, or rarely visited pages. Our goal is to ensure that the content you find on our site is accurate, up-to-date, and relevant.

The article you mention is one of the articles that was expired.

I'm attaching a copy of the PDF, but I will also send it via email, too.

[1103_madgula.pdf](https://github.com/IBM/developer/files/3131012/1103_madgula.pdf)
