### ISSUE TITLE
Missing Articles, broken links

### ISSUE THREAD

**Issue by DawnMay** [IBM/developer#77]
I have book marked two articles with valid content, but the links are now broken.  This content should not be removed as these articles remain relevant.  I often refer clients to these articles for more information as the Knowledge Center documentation is insufficient. 

https://www.ibm.com/developerworks/ibmi/library/i-how-to-use-the-batch-model-performance-tool/

https://www.ibm.com/developerworks/ibmi/library/i-new-way-to-analyze-historical-performance-data-trs/

Please return these articles.  Blindly removing content just because the publish date was a few years ago is not the correct approach. It would be better to ask the author if the content is still valid, and if so, keep it available.

Thank you, 
Dawn

**Comment by LinzSTP** [comment]
@DawnMay 
Hi Dawn,
Thanks for taking the time to send us your comments. I'm sorry you weren't able to find the pages you were looking for. I think you're aware that over the past year IBM developerWorks has transitioned to IBM Developer. As part of that transition, we've had to determine which of the thousands of articles, tutorials, and other content would migrate over to the new format and which would be retired. We based the decision largely on whether the content was  primarily product-focused or if it was outdated or rarely visited.

Unfortunately, the articles you mention are two of the articles that were retired.

I'm unable to restore the articles to IBM Developer, but I've attached a copy of the PDFs if you need to refer to them or would like to post them elsewhere.
[i-new-way-to-analyze-historical-performance-data-trs.pdf](https://github.com/IBM/developer/files/3138157/i-new-way-to-analyze-historical-performance-data-trs.pdf)
[i-how-to-use-the-batch-model-performance-tool.pdf](https://github.com/IBM/developer/files/3138160/i-how-to-use-the-batch-model-performance-tool.pdf)

BTW I did find the "How to use the Batch Model performance tool" article posted online as a downloadable PDF if you want to update your bookmark to point to it: [PDF](https://www.ibm.com/developerworks/community/wikis/form/anonymous/api/wiki/beb2d3aa-565f-41f2-b8ed-55a791b93f4f/page/156bfb04-39f6-434e-8977-a0baaffd52f4/attachment/6ab6f86f-d8f0-4e14-bbeb-c0c7a6782c6b/media/How%20to%20use%20the%20Batch%20Model%20performance%20tool.pdf)

Please contact me directly at lhalkire@us.ibm.com if there's anything else I can do to help.

**Comment by DawnMay** [comment]
That’s too bad.  These articles were very good references and are still accurate.

Here’s another one I found that is missing -  • http://www.ibm.com/developerworks/ibmi/library/i-pdiedit/index.html

Can you find the PDF of that one?

Dawn
Email:  dawnmayican@outlook.com<mailto:dawnmayican@outlook.com>
Web:  Dawnmayi.com<http://Dawnmayi.com>
Twitter:  DawnMayiCan
Blog:  http://ibmsystemsmag.com/blogs/i-can/
LinkedIn:  https://www.linkedin.com/in/dawnmay/

On May 2, 2019, at 9:22 AM, LinzSTP <notifications@github.com<mailto:notifications@github.com>> wrote:


@DawnMay<https://github.com/DawnMay>
Hi Dawn,
Thanks for taking the time to send us your comments. I'm sorry you weren't able to find the pages you were looking for. I think you're aware that over the past year IBM developerWorks has transitioned to IBM Developer. As part of that transition, we've had to determine which of the thousands of articles, tutorials, and other content would migrate over to the new format and which would be retired. We based the decision largely on whether the content was primarily product-focused or if it was outdated or rarely visited.

Unfortunately, the articles you mention are two of the articles that were retired.

I'm unable to restore the articles to IBM Developer, but I've attached a copy of the PDFs if you need to refer to them or would like to post them elsewhere.
i-new-way-to-analyze-historical-performance-data-trs.pdf<https://github.com/IBM/developer/files/3138157/i-new-way-to-analyze-historical-performance-data-trs.pdf>
i-how-to-use-the-batch-model-performance-tool.pdf<https://github.com/IBM/developer/files/3138160/i-how-to-use-the-batch-model-performance-tool.pdf>

BTW I did find the "How to use the Batch Model performance tool" article posted online as a downloadable PDF if you want to update your bookmark to point to it: PDF<https://www.ibm.com/developerworks/community/wikis/form/anonymous/api/wiki/beb2d3aa-565f-41f2-b8ed-55a791b93f4f/page/156bfb04-39f6-434e-8977-a0baaffd52f4/attachment/6ab6f86f-d8f0-4e14-bbeb-c0c7a6782c6b/media/How%20to%20use%20the%20Batch%20Model%20performance%20tool.pdf>

Please contact me directly at lhalkire@us.ibm.com<mailto:lhalkire@us.ibm.com> if there's anything else I can do to help.

**Comment by DawnMay** [comment]
And here’s another broken link - this is an article I wrote and need to get this back.  I point clients to this all the time.

"IBM i wait accounting”<https://www.ibm.com/developerworks/ibmi/library/i-ibmi-wait-accounting/>



Dawn
Email:  dawnmayican@outlook.com<mailto:dawnmayican@outlook.com>
Web:  Dawnmayi.com<http://Dawnmayi.com>
Twitter:  DawnMayiCan
Blog:  http://ibmsystemsmag.com/blogs/i-can/
LinkedIn:  https://www.linkedin.com/in/dawnmay/

On May 2, 2019, at 9:22 AM, LinzSTP <notifications@github.com<mailto:notifications@github.com>> wrote:


@DawnMay<https://github.com/DawnMay>
Hi Dawn,
Thanks for taking the time to send us your comments. I'm sorry you weren't able to find the pages you were looking for. I think you're aware that over the past year IBM developerWorks has transitioned to IBM Developer. As part of that transition, we've had to determine which of the thousands of articles, tutorials, and other content would migrate over to the new format and which would be retired. We based the decision largely on whether the content was primarily product-focused or if it was outdated or rarely visited.

Unfortunately, the articles you mention are two of the articles that were retired.

I'm unable to restore the articles to IBM Developer, but I've attached a copy of the PDFs if you need to refer to them or would like to post them elsewhere.
i-new-way-to-analyze-historical-performance-data-trs.pdf<https://github.com/IBM/developer/files/3138157/i-new-way-to-analyze-historical-performance-data-trs.pdf>
i-how-to-use-the-batch-model-performance-tool.pdf<https://github.com/IBM/developer/files/3138160/i-how-to-use-the-batch-model-performance-tool.pdf>

BTW I did find the "How to use the Batch Model performance tool" article posted online as a downloadable PDF if you want to update your bookmark to point to it: PDF<https://www.ibm.com/developerworks/community/wikis/form/anonymous/api/wiki/beb2d3aa-565f-41f2-b8ed-55a791b93f4f/page/156bfb04-39f6-434e-8977-a0baaffd52f4/attachment/6ab6f86f-d8f0-4e14-bbeb-c0c7a6782c6b/media/How%20to%20use%20the%20Batch%20Model%20performance%20tool.pdf>

Please contact me directly at lhalkire@us.ibm.com<mailto:lhalkire@us.ibm.com> if there's anything else I can do to help.

**Comment by LinzSTP** [comment]
Here you go. 
[i-pdiedit.pdf](https://github.com/IBM/developer/files/3138371/i-pdiedit.pdf)

**Comment by DawnMay** [comment]
I found another missing article.  This is another one I wrote and is now missing.

www.ibm.com/developerworks/ibmi/library/i-granular-security/<http://www.ibm.com/developerworks/ibmi/library/i-granular-security/>

However, the reference PDF is still available.  Both should be available.

https://www.ibm.com/developerworks/ibmi/library/i-granular-security/function_usage_id.pdf


Dawn
Email:  dawnmayican@outlook.com<mailto:dawnmayican@outlook.com>
Web:  Dawnmayi.com<http://Dawnmayi.com>
Twitter:  DawnMayiCan
Blog:  http://ibmsystemsmag.com/blogs/i-can/
LinkedIn:  https://www.linkedin.com/in/dawnmay/

On May 2, 2019, at 9:22 AM, LinzSTP <notifications@github.com<mailto:notifications@github.com>> wrote:


@DawnMay<https://github.com/DawnMay>
Hi Dawn,
Thanks for taking the time to send us your comments. I'm sorry you weren't able to find the pages you were looking for. I think you're aware that over the past year IBM developerWorks has transitioned to IBM Developer. As part of that transition, we've had to determine which of the thousands of articles, tutorials, and other content would migrate over to the new format and which would be retired. We based the decision largely on whether the content was primarily product-focused or if it was outdated or rarely visited.

Unfortunately, the articles you mention are two of the articles that were retired.

I'm unable to restore the articles to IBM Developer, but I've attached a copy of the PDFs if you need to refer to them or would like to post them elsewhere.
i-new-way-to-analyze-historical-performance-data-trs.pdf<https://github.com/IBM/developer/files/3138157/i-new-way-to-analyze-historical-performance-data-trs.pdf>
i-how-to-use-the-batch-model-performance-tool.pdf<https://github.com/IBM/developer/files/3138160/i-how-to-use-the-batch-model-performance-tool.pdf>

BTW I did find the "How to use the Batch Model performance tool" article posted online as a downloadable PDF if you want to update your bookmark to point to it: PDF<https://www.ibm.com/developerworks/community/wikis/form/anonymous/api/wiki/beb2d3aa-565f-41f2-b8ed-55a791b93f4f/page/156bfb04-39f6-434e-8977-a0baaffd52f4/attachment/6ab6f86f-d8f0-4e14-bbeb-c0c7a6782c6b/media/How%20to%20use%20the%20Batch%20Model%20performance%20tool.pdf>

Please contact me directly at lhalkire@us.ibm.com<mailto:lhalkire@us.ibm.com> if there's anything else I can do to help.

**Comment by LinzSTP** [comment]
Hi Dawn,

As I mentioned via email earlier today, we just heard from the IBM Developer management team that they are in the process of restoring the content that was expired from developerWorks and it should be back up in the next week or so.  They're also working on a longer term solution for a content archive, and will communicate the details in advance as the plans are finalized.

I've attached PDF versions of the other 2 expired articles you've mentioned  in case you have an immediate need for them.

[i-ibmi-wait-accounting.pdf](https://github.com/IBM/developer/files/3141814/i-ibmi-wait-accounting.pdf)
[i-granular-security.pdf](https://github.com/IBM/developer/files/3141818/i-granular-security.pdf)

Thanks!
Linda

**Comment by DawnMay** [comment]
Thank you!!!  This is an excellent decision.

Dawn
Email:  dawnmayican@outlook.com<mailto:dawnmayican@outlook.com>
Web:  Dawnmayi.com<http://Dawnmayi.com>
Twitter:  DawnMayiCan
Blog:  http://ibmsystemsmag.com/blogs/i-can/
LinkedIn:  https://www.linkedin.com/in/dawnmay/

On May 3, 2019, at 8:24 AM, LinzSTP <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dawn,

As I mentioned via email earlier today, we just heard from the IBM Developer management team that they are in the process of restoring the content that was expired from developerWorks and it should be back up in the next week or so. They're also working on a longer term solution for a content archive, and will communicate the details in advance as the plans are finalized.

I've attached PDF versions of the other 2 expired articles you've mentioned in case you have an immediate need for them.

i-ibmi-wait-accounting.pdf<https://github.com/IBM/developer/files/3141814/i-ibmi-wait-accounting.pdf>
i-granular-security.pdf<https://github.com/IBM/developer/files/3141818/i-granular-security.pdf>

Thanks!
Linda
